/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

/**
 *
 * @author Raj Sami
 */
public class AdminControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminControlPanel
     */
    public AdminControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        addBusDetailsMi = new javax.swing.JMenuItem();
        editbusMenu = new javax.swing.JMenuItem();
        deleteBusMenu = new javax.swing.JMenuItem();
        allBussDetailsMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        addEmployeMenu = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        assignBus = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        addBookingMenu = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Welcome : Admin");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu5.setText("Manage bus");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(0, 0, 0, 20));

        addBusDetailsMi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        addBusDetailsMi.setText("Add Bus Details");
        addBusDetailsMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusDetailsMiActionPerformed(evt);
            }
        });
        jMenu5.add(addBusDetailsMi);

        editbusMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        editbusMenu.setText("Edit Bus Details");
        editbusMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbusMenuActionPerformed(evt);
            }
        });
        jMenu5.add(editbusMenu);

        deleteBusMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        deleteBusMenu.setText("Delete Bus Details");
        deleteBusMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBusMenuActionPerformed(evt);
            }
        });
        jMenu5.add(deleteBusMenu);

        allBussDetailsMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        allBussDetailsMenu.setText("All Bus Details");
        allBussDetailsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBussDetailsMenuActionPerformed(evt);
            }
        });
        jMenu5.add(allBussDetailsMenu);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Bus time");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 10, 0, 10));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add Bus Time");
        jMenuItem1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuItem1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Edit Bus Time");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Delete Bus Time");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("All Bus Time");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bus fate");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem9.setText("Add Bus Fare");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem10.setText("Edit Bus Fare");
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Employee");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 10, 0, 10));

        addEmployeMenu.setText("Add Employee");
        addEmployeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeMenuActionPerformed(evt);
            }
        });
        jMenu4.add(addEmployeMenu);

        jMenuItem12.setText("Edit Employee");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Delete Employee");
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("All Employee");
        jMenu4.add(jMenuItem14);

        assignBus.setText("Assign Bus");
        assignBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBusActionPerformed(evt);
            }
        });
        jMenu4.add(assignBus);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Booking ");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 0, 0, 10));

        addBookingMenu.setText("Add Booking");
        addBookingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingMenuActionPerformed(evt);
            }
        });
        jMenu6.add(addBookingMenu);

        jMenuItem18.setText("Booking Details");
        jMenu6.add(jMenuItem18);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Manege admin");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(0, 0, 0, 10));

        jMenuItem15.setText("Add Admin");
        jMenu3.add(jMenuItem15);

        jMenuItem16.setText("Delete Admin");
        jMenu3.add(jMenuItem16);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Report");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem17.setText("betwwen Date");
        jMenu7.add(jMenuItem17);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 633, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuItem1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1AncestorAdded

    private void allBussDetailsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBussDetailsMenuActionPerformed
        // TODO add your handling code here:
        AllBusDetails albd = new AllBusDetails();
        jDesktopPane1.add(albd);
        albd.show();
    }//GEN-LAST:event_allBussDetailsMenuActionPerformed

    private void addBusDetailsMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusDetailsMiActionPerformed
        // TODO add your handling code here:
        AddBusDetails abd = new AddBusDetails();
        jDesktopPane1.add(abd);
        abd.show();
    }//GEN-LAST:event_addBusDetailsMiActionPerformed

    private void addEmployeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeMenuActionPerformed
        // TODO add your handling code here:
        Addemployee ae = new Addemployee();
        jDesktopPane1.add(ae);
        ae.show();
    }//GEN-LAST:event_addEmployeMenuActionPerformed

    private void assignBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBusActionPerformed
        // TODO add your handling code here:
        AssignBus ab = new AssignBus();
        jDesktopPane1.add(ab);
        ab.show();
    }//GEN-LAST:event_assignBusActionPerformed

    private void addBookingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingMenuActionPerformed
        // TODO add your handling code here:
        AddBooking ab = new AddBooking();
        jDesktopPane1.add(ab);
        ab.show();
    }//GEN-LAST:event_addBookingMenuActionPerformed

    private void editbusMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbusMenuActionPerformed
        // TODO add your handling code here:
        EditBusDetails eb =new EditBusDetails();
        jDesktopPane1.add(eb);
        eb.show();
    }//GEN-LAST:event_editbusMenuActionPerformed

    private void deleteBusMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusMenuActionPerformed
        // TODO add your handling code here:
        DeleteBusDetails db = new DeleteBusDetails();
        jDesktopPane1.add(db);
        db.show();
    }//GEN-LAST:event_deleteBusMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBookingMenu;
    private javax.swing.JMenuItem addBusDetailsMi;
    private javax.swing.JMenuItem addEmployeMenu;
    private javax.swing.JMenuItem allBussDetailsMenu;
    private javax.swing.JMenuItem assignBus;
    private javax.swing.JMenuItem deleteBusMenu;
    private javax.swing.JMenuItem editbusMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
