/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test;

import com.dao.CRUDst;
import com.model.Teacher;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fee_Amanillah
 */
public class StaffFrom extends javax.swing.JFrame {
 DefaultTableModel model = null;
    String imgPath;

    /**
     * Creates new form NewJFrame
     */
    public StaffFrom() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
         model = (DefaultTableModel) showtable.getModel();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        joindate = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        addImage = new javax.swing.JButton();
        showimage = new javax.swing.JLabel();
        submitt = new javax.swing.JButton();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fathern = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mothern = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        birthdate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        joindate.setBackground(new java.awt.Color(104, 0, 78));
        joindate.setName(""); // NOI18N
        joindate.setPreferredSize(new java.awt.Dimension(550, 660));

        jPanel1.setBackground(new java.awt.Color(104, 0, 78));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "Joining From", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 210, 180));
        jLabel1.setText("Last Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(118, 273, 71, 15);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname);
        lname.setBounds(198, 268, 219, 27);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 210, 180));
        jLabel2.setText("Father's Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(94, 318, 95, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 210, 180));
        jLabel5.setText("Sex: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(157, 607, 33, 15);

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        male.setForeground(new java.awt.Color(246, 210, 180));
        male.setText("Male");
        male.setOpaque(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(196, 603, 53, 23);

        female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        female.setForeground(new java.awt.Color(246, 210, 180));
        female.setSelected(true);
        female.setText("Female");
        female.setOpaque(false);
        jPanel1.add(female);
        female.setBounds(246, 603, 69, 23);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(246, 210, 180));
        jLabel12.setText("Date of Birth:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(106, 518, 83, 15);

        addImage.setBackground(new java.awt.Color(246, 210, 180));
        addImage.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        addImage.setText("+");
        addImage.setBorder(null);
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });
        jPanel1.add(addImage);
        addImage.setBounds(530, 160, 21, 22);

        showimage.setBackground(new java.awt.Color(246, 210, 180));
        showimage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showimage.setFocusTraversalPolicyProvider(true);
        showimage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showimage.setOpaque(true);
        jPanel1.add(showimage);
        showimage.setBounds(430, 30, 131, 153);

        submitt.setBackground(new java.awt.Color(255, 51, 51));
        submitt.setText("Submitt");
        submitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittActionPerformed(evt);
            }
        });
        jPanel1.add(submitt);
        submitt.setBounds(460, 321, 109, 31);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(198, 227, 219, 27);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 210, 180));
        jLabel9.setText("First Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(117, 232, 72, 15);

        fathern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernActionPerformed(evt);
            }
        });
        jPanel1.add(fathern);
        fathern.setBounds(198, 313, 219, 27);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 210, 180));
        jLabel10.setText("Mother's Name:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(91, 363, 98, 15);

        mothern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothernActionPerformed(evt);
            }
        });
        jPanel1.add(mothern);
        mothern.setBounds(198, 358, 219, 27);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Cancel");
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 544, 109, 31);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(246, 210, 180));
        jLabel11.setText("Mobile No.:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(117, 406, 72, 15);

        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        jPanel1.add(mobile);
        mobile.setBounds(198, 403, 219, 27);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);
        email.setBounds(198, 448, 219, 27);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(246, 210, 180));
        jLabel14.setText("E-Mail:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(146, 453, 43, 15);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(246, 210, 180));
        jLabel15.setText("Joining Date");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(106, 563, 83, 15);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(198, 557, 219, 28);
        jPanel1.add(birthdate);
        birthdate.setBounds(198, 505, 219, 28);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 401, 109, 31);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 477, 109, 31);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Cancel");
        jPanel1.add(jButton4);
        jButton4.setBounds(460, 264, 109, 31);

        jPanel2.setBackground(new java.awt.Color(104, 0, 78));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), "Teachers Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        showtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Frist Name", "Last Name", "Father's Name", "Mother's Name", "Mobile", "E=mail", "sex", "Birth Date", "Joining Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(showtable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout joindateLayout = new javax.swing.GroupLayout(joindate);
        joindate.setLayout(joindateLayout);
        joindateLayout.setHorizontalGroup(
            joindateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joindateLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        joindateLayout.setVerticalGroup(
            joindateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joindateLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(joindateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(joindate, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(joindate, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fathernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathernActionPerformed

    private void mothernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothernActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed
    public ImageIcon ResizeImage(String imaPath) {
        ImageIcon myImage = new ImageIcon(imaPath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(showimage.getWidth(), showimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            showimage.setIcon(ResizeImage(path));
            imgPath = path;
    }//GEN-LAST:event_addImageActionPerformed
    }
    private void submittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submittActionPerformed
        String sfName = fname.getText();

        String slName = lname.getText();

        String sfatherN = fathern.getText();

        String smotherN = mothern.getText();

        String smobile = mobile.getText();
        String sEmail = email.getText();

        DateFormat formate1 = new SimpleDateFormat("yyyy-MM-dd");
        String birthDate = formate1.format(birthdate.getDate());
        
        DateFormat formate2 = new SimpleDateFormat("yyyy-MM-dd");
        String joinDate = formate2.format(jDateChooser1.getDate());
        String sex = male.getText();

       
        String simage = imgPath;
        System.out.println(simage);

      Teacher teacher =new Teacher(sfName, slName, sfatherN, smotherN, smobile, sEmail, birthDate, sex, joinDate, simage);
        int a = CRUDst.inserData(teacher);
        System.out.println(a);
        if (a > 0) {
            JOptionPane.showMessageDialog(this.email, "Information Successful");
        } else {
            JOptionPane.showMessageDialog(this.email, "Information Failed");
        }

    }//GEN-LAST:event_submittActionPerformed
 public void showTableData() {
        List<Teacher> list;
        try {
            list = CRUDst.readData();
            for (Teacher tr : list) {
                model.addRow(new Object[]{ tr.getfName(), tr.getlName(), tr.getFatherName(), tr.getMotherName(), tr.getMobile(), tr.geteMail(), tr.getSex(), tr.getBirthDate(), tr.getJoinDate()});

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImage;
    private com.toedter.calendar.JDateChooser birthdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fathern;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel joindate;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField mothern;
    private javax.swing.JLabel showimage;
    private javax.swing.JTable showtable;
    private javax.swing.JButton submitt;
    // End of variables declaration//GEN-END:variables
}
